<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;

use Unified\Unified_to\Models\Shared;
use Unified\Unified_to\Utils\SpeakeasyMetadata;
class CreateAdsGroupRequest
{
    /**
     *
     * @var Shared\AdsGroup $adsGroup
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Shared\AdsGroup $adsGroup;

    /**
     * ID of the connection
     *
     * @var string $connectionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=connection_id')]
    public string $connectionId;

    /**
     * Comma-delimited fields to return
     *
     * @var ?array<CreateAdsGroupQueryParamFields> $fields
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=fields')]
    public ?array $fields = null;

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
     *
     * @var ?string $raw
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=raw')]
    public ?string $raw = null;

    /**
     * @param  Shared\AdsGroup  $adsGroup
     * @param  string  $connectionId
     * @param  ?array<CreateAdsGroupQueryParamFields>  $fields
     * @param  ?string  $raw
     * @phpstan-pure
     */
    public function __construct(Shared\AdsGroup $adsGroup, string $connectionId, ?array $fields = null, ?string $raw = null)
    {
        $this->adsGroup = $adsGroup;
        $this->connectionId = $connectionId;
        $this->fields = $fields;
        $this->raw = $raw;
    }
}