<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;

use Unified\Unified_to\Models\Shared;
use Unified\Unified_to\Utils\SpeakeasyMetadata;
class CreateAtsActivityRequest
{
    /**
     *
     * @var ?Shared\AtsActivity $atsActivity
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?Shared\AtsActivity $atsActivity = null;

    /**
     * ID of the connection
     *
     * @var string $connectionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=connection_id')]
    public string $connectionId;

    /**
     * @param  ?string  $connectionId
     * @param  ?Shared\AtsActivity  $atsActivity
     */
    public function __construct(?string $connectionId = null, ?Shared\AtsActivity $atsActivity = null)
    {
        $this->connectionId = $connectionId;
        $this->atsActivity = $atsActivity;
    }
}