<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;


enum GetHrisTimeoffQueryParamFields: string
{
    case Id = 'id';
    case CreatedAt = 'created_at';
    case UpdatedAt = 'updated_at';
    case UserId = 'user_id';
    case CompanyId = 'company_id';
    case StartAt = 'start_at';
    case EndAt = 'end_at';
    case IsPaid = 'is_paid';
    case Status = 'status';
    case ApproverUserId = 'approver_user_id';
    case ApprovedAt = 'approved_at';
    case Comments = 'comments';
    case Raw = 'raw';
    case Reason = 'reason';
}
