<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;

use Unified\Unified_to\Utils\SpeakeasyMetadata;
class ListAnalyticsSessions2Request
{
    /**
     * ID of the connection
     *
     * @var string $connectionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=connection_id')]
    public string $connectionId;

    /**
     * The end date to filter by (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
     *
     * @var ?string $endLt
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end_lt')]
    public ?string $endLt = null;

    /**
     * Fields to return
     *
     * @var ?array<\Unified\Unified_to\Models\Operations\ListAnalyticsSessions2QueryParamFields> $fields
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=fields')]
    public ?array $fields = null;

    /**
     *
     * @var ?float $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?float $limit = null;

    /**
     * The analytics medium to filter by
     *
     * @var ?string $medium
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=medium')]
    public ?string $medium = null;

    /**
     *
     * @var ?float $offset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?float $offset = null;

    /**
     *
     * @var ?string $order
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order')]
    public ?string $order = null;

    /**
     * The analytics property ID to filter by
     *
     * @var ?string $propertyId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=property_id')]
    public ?string $propertyId = null;

    /**
     * Query string to search. eg. email address or name
     *
     * @var ?string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=query')]
    public ?string $query = null;

    /**
     * Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
     *
     * @var ?string $raw
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=raw')]
    public ?string $raw = null;

    /**
     *
     * @var ?string $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?string $sort = null;

    /**
     * The analytics source to filter by
     *
     * @var ?string $source
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=source')]
    public ?string $source = null;

    /**
     * The start date to filter by (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
     *
     * @var ?string $startGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start_gte')]
    public ?string $startGte = null;

    /**
     * Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
     *
     * @var ?string $updatedGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=updated_gte')]
    public ?string $updatedGte = null;

    /**
     * The analytics visitor ID to filter by
     *
     * @var ?string $visitorId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=visitor_id')]
    public ?string $visitorId = null;

    /**
     * @param  string  $connectionId
     * @param  ?string  $endLt
     * @param  ?array<\Unified\Unified_to\Models\Operations\ListAnalyticsSessions2QueryParamFields>  $fields
     * @param  ?float  $limit
     * @param  ?string  $medium
     * @param  ?float  $offset
     * @param  ?string  $order
     * @param  ?string  $propertyId
     * @param  ?string  $query
     * @param  ?string  $raw
     * @param  ?string  $sort
     * @param  ?string  $source
     * @param  ?string  $startGte
     * @param  ?string  $updatedGte
     * @param  ?string  $visitorId
     * @phpstan-pure
     */
    public function __construct(string $connectionId, ?string $endLt = null, ?array $fields = null, ?float $limit = null, ?string $medium = null, ?float $offset = null, ?string $order = null, ?string $propertyId = null, ?string $query = null, ?string $raw = null, ?string $sort = null, ?string $source = null, ?string $startGte = null, ?string $updatedGte = null, ?string $visitorId = null)
    {
        $this->connectionId = $connectionId;
        $this->endLt = $endLt;
        $this->fields = $fields;
        $this->limit = $limit;
        $this->medium = $medium;
        $this->offset = $offset;
        $this->order = $order;
        $this->propertyId = $propertyId;
        $this->query = $query;
        $this->raw = $raw;
        $this->sort = $sort;
        $this->source = $source;
        $this->startGte = $startGte;
        $this->updatedGte = $updatedGte;
        $this->visitorId = $visitorId;
    }
}