<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;

use Unified\Unified_to\Utils\SpeakeasyMetadata;
class ListMessagingMessagesRequest
{
    /**
     * ID of the connection
     *
     * @var string $connectionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=connection_id')]
    public string $connectionId;

    /**
     *
     * @var ?string $channelId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=channel_id')]
    public ?string $channelId = null;

    /**
     *
     * @var ?string $endLe
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end_le')]
    public ?string $endLe = null;

    /**
     * Comma-delimited fields to return
     *
     * @var ?array<string> $fields
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=fields')]
    public ?array $fields = null;

    /**
     *
     * @var ?float $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?float $limit = null;

    /**
     *
     * @var ?float $offset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?float $offset = null;

    /**
     *
     * @var ?string $order
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order')]
    public ?string $order = null;

    /**
     *
     * @var ?string $parentId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=parent_id')]
    public ?string $parentId = null;

    /**
     * Query string to search. eg. email address or name
     *
     * @var ?string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=query')]
    public ?string $query = null;

    /**
     *
     * @var ?string $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?string $sort = null;

    /**
     *
     * @var ?string $startGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start_gte')]
    public ?string $startGte = null;

    /**
     * Return only results whose updated date is equal or greater to this value
     *
     * @var ?\DateTime $updatedGte
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=updated_gte,dateTimeFormat=Y-m-d\TH:i:s.up')]
    public ?\DateTime $updatedGte = null;

    /**
     * @param  string  $connectionId
     * @param  ?string  $channelId
     * @param  ?string  $endLe
     * @param  ?array<string>  $fields
     * @param  ?float  $limit
     * @param  ?float  $offset
     * @param  ?string  $order
     * @param  ?string  $parentId
     * @param  ?string  $query
     * @param  ?string  $sort
     * @param  ?string  $startGte
     * @param  ?\DateTime  $updatedGte
     * @phpstan-pure
     */
    public function __construct(string $connectionId, ?string $channelId = null, ?string $endLe = null, ?array $fields = null, ?float $limit = null, ?float $offset = null, ?string $order = null, ?string $parentId = null, ?string $query = null, ?string $sort = null, ?string $startGte = null, ?\DateTime $updatedGte = null)
    {
        $this->connectionId = $connectionId;
        $this->channelId = $channelId;
        $this->endLe = $endLe;
        $this->fields = $fields;
        $this->limit = $limit;
        $this->offset = $offset;
        $this->order = $order;
        $this->parentId = $parentId;
        $this->query = $query;
        $this->sort = $sort;
        $this->startGte = $startGte;
        $this->updatedGte = $updatedGte;
    }
}