<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;


enum ListAccountingContactsQueryParamFields: string
{
    case Id = 'id';
    case CreatedAt = 'created_at';
    case UpdatedAt = 'updated_at';
    case Name = 'name';
    case FirstName = 'first_name';
    case LastName = 'last_name';
    case Emails = 'emails';
    case Telephones = 'telephones';
    case Currency = 'currency';
    case BillingAddress = 'billing_address';
    case ShippingAddress = 'shipping_address';
    case IsActive = 'is_active';
    case TaxExemption = 'tax_exemption';
    case TaxNumber = 'tax_number';
    case IsCustomer = 'is_customer';
    case IsSupplier = 'is_supplier';
    case PortalUrl = 'portal_url';
    case PaymentMethods = 'payment_methods';
    case CompanyName = 'company_name';
    case Identification = 'identification';
    case AssociatedContacts = 'associated_contacts';
    case Raw = 'raw';
}
