<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;


enum PatchCrmCompanyQueryParamFields: string
{
    case Id = 'id';
    case CreatedAt = 'created_at';
    case UpdatedAt = 'updated_at';
    case Name = 'name';
    case DealIds = 'deal_ids';
    case ContactIds = 'contact_ids';
    case Emails = 'emails';
    case Telephones = 'telephones';
    case Websites = 'websites';
    case Address = 'address';
    case IsActive = 'is_active';
    case Tags = 'tags';
    case Description = 'description';
    case Industry = 'industry';
    case LinkUrls = 'link_urls';
    case Employees = 'employees';
    case Timezone = 'timezone';
    case UserId = 'user_id';
    case Metadata = 'metadata';
    case Domains = 'domains';
    case Raw = 'raw';
}
