<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;

use \Unified\Unified_to\Utils\SpeakeasyMetadata;
class PatchCrmConnectionIdEventIdContactContactIdRequest
{
    /**
     * ID of the connection
     * 
     * @var string $connectionId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=connection_id')]
    public string $connectionId;
    
    /**
     * ID of the contact
     * 
     * @var string $contactId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=contact_id')]
    public string $contactId;
    
    /**
     * ID of the Event
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->connectionId = "";
		$this->contactId = "";
		$this->id = "";
	}
}
