<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Operations;


enum PatchTaskTaskQueryParamFields: string
{
    case Id = 'id';
    case CreatedAt = 'created_at';
    case UpdatedAt = 'updated_at';
    case Name = 'name';
    case ProjectId = 'project_id';
    case ParentId = 'parent_id';
    case CompletedAt = 'completed_at';
    case Status = 'status';
    case Notes = 'notes';
    case DueAt = 'due_at';
    case Priority = 'priority';
    case AssignedUserIds = 'assigned_user_ids';
    case CreatorUserId = 'creator_user_id';
    case FollowerUserIds = 'follower_user_ids';
    case GroupIds = 'group_ids';
    case Tags = 'tags';
    case Url = 'url';
    case AttachmentIds = 'attachment_ids';
    case Metadata = 'metadata';
    case HasChildren = 'has_children';
    case Raw = 'raw';
}
