<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


class EnrichTelephone
{
    /**
     *
     * @var string $telephone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('telephone')]
    public string $telephone;

    /**
     *
     * @var ?EnrichTelephoneType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\EnrichTelephoneType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?EnrichTelephoneType $type = null;

    /**
     * @param  string  $telephone
     * @param  ?EnrichTelephoneType  $type
     */
    public function __construct(string $telephone, ?EnrichTelephoneType $type = null)
    {
        $this->telephone = $telephone;
        $this->type = $type;
    }
}