<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


class GenaiTask
{
    /**
     *
     * @var ?string $agentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('agent_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $agentId = null;

    /**
     *
     * @var ?\DateTime $completedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completed_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $completedAt = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     *
     * @var ?float $filesChanged
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('files_changed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $filesChanged = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $instructions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('instructions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $instructions = null;

    /**
     *
     * @var ?float $linesAdded
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lines_added')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $linesAdded = null;

    /**
     *
     * @var ?float $linesDeleted
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lines_deleted')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $linesDeleted = null;

    /**
     * The conversation between the user and the coding agent.
     *
     * @var ?array<\Unified\Unified_to\Models\Shared\GenaiContent> $messages
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('messages')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\GenaiContent>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $messages = null;

    /**
     *
     * @var ?string $modelId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('model_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $modelId = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     *
     * @var ?string $pullrequestUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pullrequest_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $pullrequestUrl = null;

    /**
     * $raw
     *
     * @var ?array<string, mixed> $raw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $raw = null;

    /**
     *
     * @var ?string $repoUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('repo_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $repoUrl = null;

    /**
     *
     * @var ?string $sourceBranchIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_branch_identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceBranchIdentifier = null;

    /**
     *
     * @var ?\DateTime $startedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('started_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $startedAt = null;

    /**
     *
     * @var ?\Unified\Unified_to\Models\Shared\GenaiTaskStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\GenaiTaskStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GenaiTaskStatus $status = null;

    /**
     *
     * @var ?string $summary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('summary')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $summary = null;

    /**
     *
     * @var ?string $targetBranchIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('target_branch_identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $targetBranchIdentifier = null;

    /**
     *
     * @var ?float $tokensUsed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tokens_used')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $tokensUsed = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     *
     * @var ?string $userId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('user_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $userId = null;

    /**
     *
     * @var ?string $webUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('web_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $webUrl = null;

    /**
     * @param  ?string  $agentId
     * @param  ?\DateTime  $completedAt
     * @param  ?\DateTime  $createdAt
     * @param  ?string  $error
     * @param  ?float  $filesChanged
     * @param  ?string  $id
     * @param  ?string  $instructions
     * @param  ?float  $linesAdded
     * @param  ?float  $linesDeleted
     * @param  ?array<\Unified\Unified_to\Models\Shared\GenaiContent>  $messages
     * @param  ?string  $modelId
     * @param  ?string  $name
     * @param  ?string  $organizationId
     * @param  ?string  $pullrequestUrl
     * @param  ?array<string, mixed>  $raw
     * @param  ?string  $repoUrl
     * @param  ?string  $sourceBranchIdentifier
     * @param  ?\DateTime  $startedAt
     * @param  ?\Unified\Unified_to\Models\Shared\GenaiTaskStatus  $status
     * @param  ?string  $summary
     * @param  ?string  $targetBranchIdentifier
     * @param  ?float  $tokensUsed
     * @param  ?\DateTime  $updatedAt
     * @param  ?string  $userId
     * @param  ?string  $webUrl
     * @phpstan-pure
     */
    public function __construct(?string $agentId = null, ?\DateTime $completedAt = null, ?\DateTime $createdAt = null, ?string $error = null, ?float $filesChanged = null, ?string $id = null, ?string $instructions = null, ?float $linesAdded = null, ?float $linesDeleted = null, ?array $messages = null, ?string $modelId = null, ?string $name = null, ?string $organizationId = null, ?string $pullrequestUrl = null, ?array $raw = null, ?string $repoUrl = null, ?string $sourceBranchIdentifier = null, ?\DateTime $startedAt = null, ?GenaiTaskStatus $status = null, ?string $summary = null, ?string $targetBranchIdentifier = null, ?float $tokensUsed = null, ?\DateTime $updatedAt = null, ?string $userId = null, ?string $webUrl = null)
    {
        $this->agentId = $agentId;
        $this->completedAt = $completedAt;
        $this->createdAt = $createdAt;
        $this->error = $error;
        $this->filesChanged = $filesChanged;
        $this->id = $id;
        $this->instructions = $instructions;
        $this->linesAdded = $linesAdded;
        $this->linesDeleted = $linesDeleted;
        $this->messages = $messages;
        $this->modelId = $modelId;
        $this->name = $name;
        $this->organizationId = $organizationId;
        $this->pullrequestUrl = $pullrequestUrl;
        $this->raw = $raw;
        $this->repoUrl = $repoUrl;
        $this->sourceBranchIdentifier = $sourceBranchIdentifier;
        $this->startedAt = $startedAt;
        $this->status = $status;
        $this->summary = $summary;
        $this->targetBranchIdentifier = $targetBranchIdentifier;
        $this->tokensUsed = $tokensUsed;
        $this->updatedAt = $updatedAt;
        $this->userId = $userId;
        $this->webUrl = $webUrl;
    }
}