<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


enum HrisCompensationType: string
{
    case Salary = 'SALARY';
    case Bonus = 'BONUS';
    case StockOptions = 'STOCK_OPTIONS';
    case Equity = 'EQUITY';
    case Other = 'OTHER';
}
