<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


enum LabelFormat: string
{
    case Pdf = 'PDF';
    case Png = 'PNG';
    case Zpl = 'ZPL';
    case Epl2 = 'EPL2';
    case Pdf4X6 = 'PDF_4X6';
    case Pdf4X8 = 'PDF_4X8';
    case Png4X6 = 'PNG_4X6';
    case Png4X8 = 'PNG_4X8';
}
