<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


class MessagingMessage
{
    /**
     * $attachments
     *
     * @var ?array<MessagingAttachment> $attachments
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attachments')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\MessagingAttachment>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $attachments = null;

    /**
     *
     * @var ?PropertyMessagingMessageAuthorMember $authorMember
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('author_member')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyMessagingMessageAuthorMember|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyMessagingMessageAuthorMember $authorMember = null;

    /**
     *
     * @var ?string $channelId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channel_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $channelId = null;

    /**
     * Represents the IDs of all channels to which the message is sent. Identifies the channels where the message is posted.
     *
     * @var ?array<string> $channelIds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channel_ids')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $channelIds = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * $destinationMembers
     *
     * @var ?array<MessagingMember> $destinationMembers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_members')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\MessagingMember>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $destinationMembers = null;

    /**
     *
     * @var ?bool $hasChildren
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('has_children')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $hasChildren = null;

    /**
     * $hiddenMembers
     *
     * @var ?array<MessagingMember> $hiddenMembers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hidden_members')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\MessagingMember>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $hiddenMembers = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * $mentionedMembers
     *
     * @var ?array<MessagingMember> $mentionedMembers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mentioned_members')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\MessagingMember>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $mentionedMembers = null;

    /**
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     *
     * @var ?string $messageHtml
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message_html')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $messageHtml = null;

    /**
     *
     * @var ?string $messageMarkdown
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message_markdown')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $messageMarkdown = null;

    /**
     *
     * @var ?string $parentId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parent_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $parentId = null;

    /**
     *
     * @var ?string $parentMessageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parent_message_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $parentMessageId = null;

    /**
     * $raw
     *
     * @var ?array<string, mixed> $raw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $raw = null;

    /**
     * $reactions
     *
     * @var ?array<MessagingReaction> $reactions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reactions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\MessagingReaction>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $reactions = null;

    /**
     *
     * @var ?string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reference = null;

    /**
     *
     * @var ?string $rootMessageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('root_message_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $rootMessageId = null;

    /**
     *
     * @var ?string $subject
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subject')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subject = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     *
     * @var ?string $webUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('web_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $webUrl = null;

    /**
     * @param  ?array<MessagingAttachment>  $attachments
     * @param  ?PropertyMessagingMessageAuthorMember  $authorMember
     * @param  ?string  $channelId
     * @param  ?array<string>  $channelIds
     * @param  ?\DateTime  $createdAt
     * @param  ?array<MessagingMember>  $destinationMembers
     * @param  ?bool  $hasChildren
     * @param  ?array<MessagingMember>  $hiddenMembers
     * @param  ?string  $id
     * @param  ?array<MessagingMember>  $mentionedMembers
     * @param  ?string  $message
     * @param  ?string  $messageHtml
     * @param  ?string  $messageMarkdown
     * @param  ?string  $parentId
     * @param  ?string  $parentMessageId
     * @param  ?array<string, mixed>  $raw
     * @param  ?array<MessagingReaction>  $reactions
     * @param  ?string  $reference
     * @param  ?string  $rootMessageId
     * @param  ?string  $subject
     * @param  ?\DateTime  $updatedAt
     * @param  ?string  $webUrl
     * @phpstan-pure
     */
    public function __construct(?array $attachments = null, ?PropertyMessagingMessageAuthorMember $authorMember = null, ?string $channelId = null, ?array $channelIds = null, ?\DateTime $createdAt = null, ?array $destinationMembers = null, ?bool $hasChildren = null, ?array $hiddenMembers = null, ?string $id = null, ?array $mentionedMembers = null, ?string $message = null, ?string $messageHtml = null, ?string $messageMarkdown = null, ?string $parentId = null, ?string $parentMessageId = null, ?array $raw = null, ?array $reactions = null, ?string $reference = null, ?string $rootMessageId = null, ?string $subject = null, ?\DateTime $updatedAt = null, ?string $webUrl = null)
    {
        $this->attachments = $attachments;
        $this->authorMember = $authorMember;
        $this->channelId = $channelId;
        $this->channelIds = $channelIds;
        $this->createdAt = $createdAt;
        $this->destinationMembers = $destinationMembers;
        $this->hasChildren = $hasChildren;
        $this->hiddenMembers = $hiddenMembers;
        $this->id = $id;
        $this->mentionedMembers = $mentionedMembers;
        $this->message = $message;
        $this->messageHtml = $messageHtml;
        $this->messageMarkdown = $messageMarkdown;
        $this->parentId = $parentId;
        $this->parentMessageId = $parentMessageId;
        $this->raw = $raw;
        $this->reactions = $reactions;
        $this->reference = $reference;
        $this->rootMessageId = $rootMessageId;
        $this->subject = $subject;
        $this->updatedAt = $updatedAt;
        $this->webUrl = $webUrl;
    }
}