<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


class PerformanceCycle
{
    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?\DateTime $dueAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('due_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $dueAt = null;

    /**
     *
     * @var ?\DateTime $endAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $endAt = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * $raw
     *
     * @var ?array<string, mixed> $raw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $raw = null;

    /**
     *
     * @var ?\DateTime $startAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $startAt = null;

    /**
     *
     * @var ?\Unified\Unified_to\Models\Shared\PerformanceCycleStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PerformanceCycleStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PerformanceCycleStatus $status = null;

    /**
     *
     * @var ?\Unified\Unified_to\Models\Shared\PerformanceCycleType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PerformanceCycleType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PerformanceCycleType $type = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?\DateTime  $createdAt
     * @param  ?string  $description
     * @param  ?\DateTime  $dueAt
     * @param  ?\DateTime  $endAt
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?array<string, mixed>  $raw
     * @param  ?\DateTime  $startAt
     * @param  ?\Unified\Unified_to\Models\Shared\PerformanceCycleStatus  $status
     * @param  ?\Unified\Unified_to\Models\Shared\PerformanceCycleType  $type
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?\DateTime $createdAt = null, ?string $description = null, ?\DateTime $dueAt = null, ?\DateTime $endAt = null, ?string $id = null, ?string $name = null, ?array $raw = null, ?\DateTime $startAt = null, ?PerformanceCycleStatus $status = null, ?PerformanceCycleType $type = null, ?\DateTime $updatedAt = null)
    {
        $this->createdAt = $createdAt;
        $this->description = $description;
        $this->dueAt = $dueAt;
        $this->endAt = $endAt;
        $this->id = $id;
        $this->name = $name;
        $this->raw = $raw;
        $this->startAt = $startAt;
        $this->status = $status;
        $this->type = $type;
        $this->updatedAt = $updatedAt;
    }
}