<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


class PropertyAdsCampaignTargeting
{
    /**
     *
     * @var ?PropertyAdsCampaignTargetingAudience $audience
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('audience')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingAudience|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingAudience $audience = null;

    /**
     * Brand safety (Meta: excluded_publisher_categories, etc.; Google
     *
     * @var ?PropertyAdsCampaignTargetingBrandSafety $brandSafety
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('brand_safety')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingBrandSafety|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingBrandSafety $brandSafety = null;

    /**
     *
     * @var ?PropertyAdsCampaignTargetingContent $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingContent|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingContent $content = null;

    /**
     * Demographic targeting (Meta: age_min, age_max, genders)
     *
     * @var ?PropertyAdsCampaignTargetingDemographic $demographic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('demographic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingDemographic|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingDemographic $demographic = null;

    /**
     *
     * @var ?PropertyAdsCampaignTargetingDevice $device
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('device')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingDevice|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingDevice $device = null;

    /**
     *
     * @var ?PropertyAdsCampaignTargetingGeographic $geographic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('geographic')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingGeographic|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingGeographic $geographic = null;

    /**
     * Language targeting (Meta
     *
     * @var ?PropertyAdsCampaignTargetingLanguage $language
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('language')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingLanguage|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingLanguage $language = null;

    /**
     * Optimization (Meta: targeting_automation; Google: observation vs targeting mode)
     *
     * @var ?PropertyAdsCampaignTargetingOptimization $optimization
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('optimization')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingOptimization|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingOptimization $optimization = null;

    /**
     *
     * @var ?PropertyAdsCampaignTargetingPlacement $placement
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('placement')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsCampaignTargetingPlacement|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsCampaignTargetingPlacement $placement = null;

    /**
     * $schedule
     *
     * @var ?array<AdSchedule> $schedule
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('schedule')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\AdSchedule>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $schedule = null;

    /**
     * @param  ?PropertyAdsCampaignTargetingAudience  $audience
     * @param  ?PropertyAdsCampaignTargetingBrandSafety  $brandSafety
     * @param  ?PropertyAdsCampaignTargetingContent  $content
     * @param  ?PropertyAdsCampaignTargetingDemographic  $demographic
     * @param  ?PropertyAdsCampaignTargetingDevice  $device
     * @param  ?PropertyAdsCampaignTargetingGeographic  $geographic
     * @param  ?PropertyAdsCampaignTargetingLanguage  $language
     * @param  ?PropertyAdsCampaignTargetingOptimization  $optimization
     * @param  ?PropertyAdsCampaignTargetingPlacement  $placement
     * @param  ?array<AdSchedule>  $schedule
     * @phpstan-pure
     */
    public function __construct(?PropertyAdsCampaignTargetingAudience $audience = null, ?PropertyAdsCampaignTargetingBrandSafety $brandSafety = null, ?PropertyAdsCampaignTargetingContent $content = null, ?PropertyAdsCampaignTargetingDemographic $demographic = null, ?PropertyAdsCampaignTargetingDevice $device = null, ?PropertyAdsCampaignTargetingGeographic $geographic = null, ?PropertyAdsCampaignTargetingLanguage $language = null, ?PropertyAdsCampaignTargetingOptimization $optimization = null, ?PropertyAdsCampaignTargetingPlacement $placement = null, ?array $schedule = null)
    {
        $this->audience = $audience;
        $this->brandSafety = $brandSafety;
        $this->content = $content;
        $this->demographic = $demographic;
        $this->device = $device;
        $this->geographic = $geographic;
        $this->language = $language;
        $this->optimization = $optimization;
        $this->placement = $placement;
        $this->schedule = $schedule;
    }
}