<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


class PropertyAccountingReportProfitAndLoss
{
    /**
     * @deprecated – use cost_of_goods_sold_sections instead
     *
     * @var ?array<AccountingProfitlossCategory> $costOfGoodsSold
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cost_of_goods_sold')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\AccountingProfitlossCategory>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $costOfGoodsSold = null;

    /**
     * $costOfGoodsSoldSections
     *
     * @var ?array<AccountingProfitlossSection> $costOfGoodsSoldSections
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cost_of_goods_sold_sections')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\AccountingProfitlossSection>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $costOfGoodsSoldSections = null;

    /**
     *
     * @var ?float $costOfGoodsSoldTotalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cost_of_goods_sold_total_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $costOfGoodsSoldTotalAmount = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     *
     * @var ?\DateTime $endAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('end_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $endAt = null;

    /**
     * @deprecated – use expenses_sections instead
     *
     * @var ?array<AccountingProfitlossCategory> $expenses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expenses')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\AccountingProfitlossCategory>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $expenses = null;

    /**
     * $expensesSections
     *
     * @var ?array<AccountingProfitlossSection> $expensesSections
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expenses_sections')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\AccountingProfitlossSection>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $expensesSections = null;

    /**
     *
     * @var ?float $expensesTotalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expenses_total_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $expensesTotalAmount = null;

    /**
     *
     * @var ?float $grossProfitAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('gross_profit_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $grossProfitAmount = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * @deprecated – use income_sections instead
     *
     * @var ?array<AccountingProfitlossCategory> $income
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('income')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\AccountingProfitlossCategory>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $income = null;

    /**
     * $incomeSections
     *
     * @var ?array<AccountingProfitlossSection> $incomeSections
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('income_sections')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\AccountingProfitlossSection>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $incomeSections = null;

    /**
     *
     * @var ?float $incomeTotalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('income_total_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $incomeTotalAmount = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?float $netIncomeAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_income_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $netIncomeAmount = null;

    /**
     *
     * @var ?float $netProfitAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('net_profit_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $netProfitAmount = null;

    /**
     * $raw
     *
     * @var ?array<string, mixed> $raw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $raw = null;

    /**
     *
     * @var ?\DateTime $startAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $startAt = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?array<AccountingProfitlossCategory>  $costOfGoodsSold
     * @param  ?array<AccountingProfitlossSection>  $costOfGoodsSoldSections
     * @param  ?float  $costOfGoodsSoldTotalAmount
     * @param  ?\DateTime  $createdAt
     * @param  ?string  $currency
     * @param  ?\DateTime  $endAt
     * @param  ?array<AccountingProfitlossCategory>  $expenses
     * @param  ?array<AccountingProfitlossSection>  $expensesSections
     * @param  ?float  $expensesTotalAmount
     * @param  ?float  $grossProfitAmount
     * @param  ?string  $id
     * @param  ?array<AccountingProfitlossCategory>  $income
     * @param  ?array<AccountingProfitlossSection>  $incomeSections
     * @param  ?float  $incomeTotalAmount
     * @param  ?string  $name
     * @param  ?float  $netIncomeAmount
     * @param  ?float  $netProfitAmount
     * @param  ?array<string, mixed>  $raw
     * @param  ?\DateTime  $startAt
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?array $costOfGoodsSold = null, ?array $costOfGoodsSoldSections = null, ?float $costOfGoodsSoldTotalAmount = null, ?\DateTime $createdAt = null, ?string $currency = null, ?\DateTime $endAt = null, ?array $expenses = null, ?array $expensesSections = null, ?float $expensesTotalAmount = null, ?float $grossProfitAmount = null, ?string $id = null, ?array $income = null, ?array $incomeSections = null, ?float $incomeTotalAmount = null, ?string $name = null, ?float $netIncomeAmount = null, ?float $netProfitAmount = null, ?array $raw = null, ?\DateTime $startAt = null, ?\DateTime $updatedAt = null)
    {
        $this->costOfGoodsSold = $costOfGoodsSold;
        $this->costOfGoodsSoldSections = $costOfGoodsSoldSections;
        $this->costOfGoodsSoldTotalAmount = $costOfGoodsSoldTotalAmount;
        $this->createdAt = $createdAt;
        $this->currency = $currency;
        $this->endAt = $endAt;
        $this->expenses = $expenses;
        $this->expensesSections = $expensesSections;
        $this->expensesTotalAmount = $expensesTotalAmount;
        $this->grossProfitAmount = $grossProfitAmount;
        $this->id = $id;
        $this->income = $income;
        $this->incomeSections = $incomeSections;
        $this->incomeTotalAmount = $incomeTotalAmount;
        $this->name = $name;
        $this->netIncomeAmount = $netIncomeAmount;
        $this->netProfitAmount = $netProfitAmount;
        $this->raw = $raw;
        $this->startAt = $startAt;
        $this->updatedAt = $updatedAt;
    }
}