<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


/** PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20User - an organization. */
class PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20User
{
    /**
     * $additionalManagers
     *
     * @var ?array<ScimManager> $additionalManagers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('additionalManagers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\ScimManager>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $additionalManagers = null;

    /**
     *
     * @var ?\DateTime $birthday
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('birthday')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $birthday = null;

    /**
     *
     * @var ?string $costCenter
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('costCenter')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $costCenter = null;

    /**
     *
     * @var ?string $department
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('department')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $department = null;

    /**
     *
     * @var ?string $division
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('division')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $division = null;

    /**
     *
     * @var ?string $employeeNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('employeeNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $employeeNumber = null;

    /**
     *
     * @var ?\DateTime $endDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $endDate = null;

    /**
     *
     * @var ?PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserGender $gender
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('gender')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserGender|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserGender $gender = null;

    /**
     *
     * @var ?string $level
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('level')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $level = null;

    /**
     *
     * @var ?string $location
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $location = null;

    /**
     * "id" attribute of another User.
     *
     * @var ?PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserManager $manager
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('manager')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserManager|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserManager $manager = null;

    /**
     *
     * @var ?string $organization
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organization = null;

    /**
     *
     * @var ?\DateTime $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('startDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $startDate = null;

    /**
     * @param  ?array<ScimManager>  $additionalManagers
     * @param  ?\DateTime  $birthday
     * @param  ?string  $costCenter
     * @param  ?string  $department
     * @param  ?string  $division
     * @param  ?string  $employeeNumber
     * @param  ?\DateTime  $endDate
     * @param  ?PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserGender  $gender
     * @param  ?string  $level
     * @param  ?string  $location
     * @param  ?PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserManager  $manager
     * @param  ?string  $organization
     * @param  ?\DateTime  $startDate
     */
    public function __construct(?array $additionalManagers = null, ?\DateTime $birthday = null, ?string $costCenter = null, ?string $department = null, ?string $division = null, ?string $employeeNumber = null, ?\DateTime $endDate = null, ?PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserGender $gender = null, ?string $level = null, ?string $location = null, ?PropertyScimUserUrnIetfParamsScimSchemasExtensionEnterprise20UserManager $manager = null, ?string $organization = null, ?\DateTime $startDate = null)
    {
        $this->additionalManagers = $additionalManagers;
        $this->birthday = $birthday;
        $this->costCenter = $costCenter;
        $this->department = $department;
        $this->division = $division;
        $this->employeeNumber = $employeeNumber;
        $this->endDate = $endDate;
        $this->gender = $gender;
        $this->level = $level;
        $this->location = $location;
        $this->manager = $manager;
        $this->organization = $organization;
        $this->startDate = $startDate;
    }
}