<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


class PropertyAdsReportMetricsInsertionorder
{
    /**
     * YOUTUBE_AND_PARTNERS
     *
     * @var ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderBidStrategy $bidStrategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bid_strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderBidStrategy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsReportMetricsInsertionorderBidStrategy $bidStrategy = null;

    /**
     * $budgetSegments
     *
     * @var ?array<\Unified\Unified_to\Models\Shared\AdsInsertionorderBudgetSegment> $budgetSegments
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('budget_segments')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\AdsInsertionorderBudgetSegment>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $budgetSegments = null;

    /**
     *
     * @var ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderBudgetUnit $budgetUnit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('budget_unit')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderBudgetUnit|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsReportMetricsInsertionorderBudgetUnit $budgetUnit = null;

    /**
     *
     * @var ?string $campaignId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('campaign_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $campaignId = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderFrequencyCap $frequencyCap
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('frequency_cap')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderFrequencyCap|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsReportMetricsInsertionorderFrequencyCap $frequencyCap = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderKpi $kpi
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('kpi')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderKpi|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsReportMetricsInsertionorderKpi $kpi = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     *
     * @var ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderPacing $pacing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pacing')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderPacing|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsReportMetricsInsertionorderPacing $pacing = null;

    /**
     * $raw
     *
     * @var ?array<string, mixed> $raw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $raw = null;

    /**
     *
     * @var ?string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reference = null;

    /**
     *
     * @var ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PropertyAdsReportMetricsInsertionorderStatus $status = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderBidStrategy  $bidStrategy
     * @param  ?array<\Unified\Unified_to\Models\Shared\AdsInsertionorderBudgetSegment>  $budgetSegments
     * @param  ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderBudgetUnit  $budgetUnit
     * @param  ?string  $campaignId
     * @param  ?\DateTime  $createdAt
     * @param  ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderFrequencyCap  $frequencyCap
     * @param  ?string  $id
     * @param  ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderKpi  $kpi
     * @param  ?string  $name
     * @param  ?string  $organizationId
     * @param  ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderPacing  $pacing
     * @param  ?array<string, mixed>  $raw
     * @param  ?string  $reference
     * @param  ?\Unified\Unified_to\Models\Shared\PropertyAdsReportMetricsInsertionorderStatus  $status
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?PropertyAdsReportMetricsInsertionorderBidStrategy $bidStrategy = null, ?array $budgetSegments = null, ?PropertyAdsReportMetricsInsertionorderBudgetUnit $budgetUnit = null, ?string $campaignId = null, ?\DateTime $createdAt = null, ?PropertyAdsReportMetricsInsertionorderFrequencyCap $frequencyCap = null, ?string $id = null, ?PropertyAdsReportMetricsInsertionorderKpi $kpi = null, ?string $name = null, ?string $organizationId = null, ?PropertyAdsReportMetricsInsertionorderPacing $pacing = null, ?array $raw = null, ?string $reference = null, ?PropertyAdsReportMetricsInsertionorderStatus $status = null, ?\DateTime $updatedAt = null)
    {
        $this->bidStrategy = $bidStrategy;
        $this->budgetSegments = $budgetSegments;
        $this->budgetUnit = $budgetUnit;
        $this->campaignId = $campaignId;
        $this->createdAt = $createdAt;
        $this->frequencyCap = $frequencyCap;
        $this->id = $id;
        $this->kpi = $kpi;
        $this->name = $name;
        $this->organizationId = $organizationId;
        $this->pacing = $pacing;
        $this->raw = $raw;
        $this->reference = $reference;
        $this->status = $status;
        $this->updatedAt = $updatedAt;
    }
}