<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


enum PropertyAdsReportMetricsGroupOptimizationGoal: string
{
    case Reach = 'REACH';
    case Impressions = 'IMPRESSIONS';
    case LinkClicks = 'LINK_CLICKS';
    case LandingPageViews = 'LANDING_PAGE_VIEWS';
    case Conversions = 'CONVERSIONS';
    case LeadGeneration = 'LEAD_GENERATION';
    case AppInstalls = 'APP_INSTALLS';
    case AppEngagement = 'APP_ENGAGEMENT';
    case VideoViews = 'VIDEO_VIEWS';
    case Engagement = 'ENGAGEMENT';
    case PageLikes = 'PAGE_LIKES';
    case Messages = 'MESSAGES';
}
