<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


enum ShippingTrackingEventStatus: string
{
    case Pending = 'PENDING';
    case Processing = 'PROCESSING';
    case InTransit = 'IN_TRANSIT';
    case Delivered = 'DELIVERED';
    case Exception = 'EXCEPTION';
    case Cancelled = 'CANCELLED';
    case LabelCreated = 'LABEL_CREATED';
    case PickedUp = 'PICKED_UP';
    case OutForDelivery = 'OUT_FOR_DELIVERY';
    case DeliveryAttempted = 'DELIVERY_ATTEMPTED';
    case ReturnedToSender = 'RETURNED_TO_SENDER';
    case HeldAtLocation = 'HELD_AT_LOCATION';
    case CustomsClearance = 'CUSTOMS_CLEARANCE';
    case ExceptionResolved = 'EXCEPTION_RESOLVED';
}
