<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Unified\Unified_to\Models\Shared;


class VerificationRequest
{
    /**
     *
     * @var ?string $candidateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('candidate_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $candidateId = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $packageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('package_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $packageId = null;

    /**
     * $parameters
     *
     * @var ?array<VerificationParameterInput> $parameters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parameters')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\VerificationParameterInput>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $parameters = null;

    /**
     * $profileAddresses
     *
     * @var ?array<VerificationAddress> $profileAddresses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_addresses')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\VerificationAddress>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $profileAddresses = null;

    /**
     *
     * @var ?string $profileDateOfBirth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_date_of_birth')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $profileDateOfBirth = null;

    /**
     * $profileEmails
     *
     * @var ?array<string> $profileEmails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_emails')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $profileEmails = null;

    /**
     *
     * @var ?VerificationRequestProfileGender $profileGender
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_gender')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\VerificationRequestProfileGender|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationRequestProfileGender $profileGender = null;

    /**
     *
     * @var ?string $profileIpAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_ip_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $profileIpAddress = null;

    /**
     *
     * @var ?string $profileName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $profileName = null;

    /**
     *
     * @var ?string $profileNationalIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_national_identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $profileNationalIdentifier = null;

    /**
     * $profileTelephones
     *
     * @var ?array<string> $profileTelephones
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_telephones')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $profileTelephones = null;

    /**
     * $raw
     *
     * @var ?array<string, mixed> $raw
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('raw')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $raw = null;

    /**
     *
     * @var ?\DateTime $responseCompletedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_completed_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $responseCompletedAt = null;

    /**
     * $responseDetails
     *
     * @var ?array<VerificationResponseDetail> $responseDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_details')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Unified\Unified_to\Models\Shared\VerificationResponseDetail>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $responseDetails = null;

    /**
     * report download
     *
     * @var ?array<string> $responseDownloadUrls
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_download_urls')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $responseDownloadUrls = null;

    /**
     *
     * @var ?\DateTime $responseExpiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_expires_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $responseExpiresAt = null;

    /**
     *
     * @var ?\DateTime $responseIssuedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_issued_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $responseIssuedAt = null;

    /**
     *
     * @var ?string $responseRedirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_redirect_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $responseRedirectUrl = null;

    /**
     *
     * @var ?float $responseScore
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_score')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $responseScore = null;

    /**
     *
     * @var ?string $responseSource
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_source')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $responseSource = null;

    /**
     *
     * @var ?VerificationRequestResponseStatus $responseStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('response_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Unified\Unified_to\Models\Shared\VerificationRequestResponseStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VerificationRequestResponseStatus $responseStatus = null;

    /**
     *
     * @var ?string $targetUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('target_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $targetUrl = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  ?string  $candidateId
     * @param  ?\DateTime  $createdAt
     * @param  ?string  $id
     * @param  ?string  $packageId
     * @param  ?array<VerificationParameterInput>  $parameters
     * @param  ?array<VerificationAddress>  $profileAddresses
     * @param  ?string  $profileDateOfBirth
     * @param  ?array<string>  $profileEmails
     * @param  ?VerificationRequestProfileGender  $profileGender
     * @param  ?string  $profileIpAddress
     * @param  ?string  $profileName
     * @param  ?string  $profileNationalIdentifier
     * @param  ?array<string>  $profileTelephones
     * @param  ?array<string, mixed>  $raw
     * @param  ?\DateTime  $responseCompletedAt
     * @param  ?array<VerificationResponseDetail>  $responseDetails
     * @param  ?array<string>  $responseDownloadUrls
     * @param  ?\DateTime  $responseExpiresAt
     * @param  ?\DateTime  $responseIssuedAt
     * @param  ?string  $responseRedirectUrl
     * @param  ?float  $responseScore
     * @param  ?string  $responseSource
     * @param  ?VerificationRequestResponseStatus  $responseStatus
     * @param  ?string  $targetUrl
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?string $candidateId = null, ?\DateTime $createdAt = null, ?string $id = null, ?string $packageId = null, ?array $parameters = null, ?array $profileAddresses = null, ?string $profileDateOfBirth = null, ?array $profileEmails = null, ?VerificationRequestProfileGender $profileGender = null, ?string $profileIpAddress = null, ?string $profileName = null, ?string $profileNationalIdentifier = null, ?array $profileTelephones = null, ?array $raw = null, ?\DateTime $responseCompletedAt = null, ?array $responseDetails = null, ?array $responseDownloadUrls = null, ?\DateTime $responseExpiresAt = null, ?\DateTime $responseIssuedAt = null, ?string $responseRedirectUrl = null, ?float $responseScore = null, ?string $responseSource = null, ?VerificationRequestResponseStatus $responseStatus = null, ?string $targetUrl = null, ?\DateTime $updatedAt = null)
    {
        $this->candidateId = $candidateId;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->packageId = $packageId;
        $this->parameters = $parameters;
        $this->profileAddresses = $profileAddresses;
        $this->profileDateOfBirth = $profileDateOfBirth;
        $this->profileEmails = $profileEmails;
        $this->profileGender = $profileGender;
        $this->profileIpAddress = $profileIpAddress;
        $this->profileName = $profileName;
        $this->profileNationalIdentifier = $profileNationalIdentifier;
        $this->profileTelephones = $profileTelephones;
        $this->raw = $raw;
        $this->responseCompletedAt = $responseCompletedAt;
        $this->responseDetails = $responseDetails;
        $this->responseDownloadUrls = $responseDownloadUrls;
        $this->responseExpiresAt = $responseExpiresAt;
        $this->responseIssuedAt = $responseIssuedAt;
        $this->responseRedirectUrl = $responseRedirectUrl;
        $this->responseScore = $responseScore;
        $this->responseSource = $responseSource;
        $this->responseStatus = $responseStatus;
        $this->targetUrl = $targetUrl;
        $this->updatedAt = $updatedAt;
    }
}